### ISSUE TITLE
Unable to login using standand means

### ISSUE THREAD

**Issue by kltm** [Planteome/noctua#6]
I am currently unable to login to the Planteome instance of Noctua using standard means.

* navigate to http://noctua-dev.planteome.org/
* click [Login]
* click "Sign in with GitHub"
  * accept Planteome Noctua request on GitHub (first time only)

At this point, I am returned to the barista page. While the login apparently "succeeded", it still asks for login or return

![screenshot_2017-05-09_11-10-22](https://cloud.githubusercontent.com/assets/2687900/25865624/5cf18cfa-34a8-11e7-8992-184637de95ea.png)

with the URL
 http://barista-dev.planteome.org/login/success?barista_token=null&return=http://noctua-dev.planteome.org/
and I have no way to proceed back to the application logged in.

I think the null token is key here. My guess would be that it either means that `barista-dev` could not lookup my name to give me access (possible because I have "go" access and not "planteome" access?) or that the return handshake from github back to `barista-dev` went wrong (maybe wrong domain?).

**Comment by elserj** [comment]
I added you to the Planteome organization in users.yaml.  Try it now.  Or let me know if I need to restart barista.

**Comment by kltm** [comment]
Assuming that you have given yourself maximum privileges, you will need to:
- go to http://noctua-dev.planteome.org
- login and return to the landing page
- click on [Danger Zone] tab
- click "Barista Information" [Users]
- click [User refresh]

That said, I have them and refreshed the user information; however, am still unable to login as myself. Is the correct users.yaml located in the expected location for Barista?

**Comment by kltm** [comment]
Be aware that refreshing users shuffles their colors ;)

**Comment by elserj** [comment]
I had not, but I did now.  I had to restart barista, so I think it's all good now.

**Comment by kltm** [comment]
It now works for me; just the permissions issue then.
A barista restart should not be necessary, but it is certainly effective as well.
