### ISSUE TITLE
"Create" button in "Create" tab in Landing page does nothing

### ISSUE THREAD

**Issue by elserj** [Planteome/noctua#9]
I thought I had a ticket for this already, but can't find it.  Anyway, the "Create" button from the "Create" tab on the landing page does nothing.  Looks to me like there is no code associated to the button on submit.  Problem seems to exist upstream, so tagging @kltm to fix.

**Comment by kltm** [comment]
As this is an issue upstream that is not planteome-specific, go ahead and create the issue upstream.

**Comment by elserj** [comment]
Create tab was removed from templates/noctua_landing.tmpl.  Can't find the specific commit for it for some reason, but it's there.
